### PR TITLE
mapping aws_appmesh

### PR DESCRIPTION
**Pull request by PatMyron**
prev: https://github.com/terraform-linters/tflint-ruleset-aws/pull/218
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_gateway_route
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_gateway
https://github.com/aws/aws-sdk-go/blob/main/models/apis/appmesh/2019-01-25/api-2.json

### CODE REVIEW

**Review by wata727 — APPROVED** [review]
👌

**Comment by wata727** [comment]
Hi @PatMyron, thank you for your great works!
Some pull requests have been conflicted and have not been merged., so please resolve them first.

By the way, are you interested in joining our org as an AWS ruleset maintainer?
Currently, we do not have a dedicated maintainer, so we do not have sufficient support for each provider. I would be very happy if you could help us.

**Comment by PatMyron** [comment]
@wata727 I'd love that, thanks!

**Comment by PatMyron** [comment]
also do maintainers talk anywhere else like Slack? or is all the discussion in these repos?

**Comment by wata727** [comment]
Thank you! Invited you to @terraform-linters/tflint-aws-maintainers 
All discussions are here. If you need a place for private discussion, I would like to consider it, but I prefer open discussions.

**Comment by PatMyron** [comment]
@wata727 also interested in helping triage the Google/Azure ruleset repos if you're okay with that

**Comment by wata727** [comment]
Sure!

**Comment by PatMyron** [comment]
@wata727 could I get permissions to close issues in those repos? Would like to start combining similar issues

**Comment by wata727** [comment]
OK, I added you to Google/Azure ruleset contributors team.

**Comment by PatMyron** [comment]
@wata727 also don't mind handling the `dependabot` PRs for those repos if you all want help merging those going forward

**Pull request merged**
